import getCurrentUser from "./actions/getCurrentUser";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Nunito } from "next/font/google";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {

    const currentUser = await getCurrentUser();

	return (
		<html lang="en">
			<body className={font.className}>
				<Navbar currentUser={currentUser}/>
				{children}
			</body>
		</html>
	);
}
